// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  Docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'GettingStarted/Introduction',
        'GettingStarted/Litepaper',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge Base',
      items: [
        'KnowledgeBase/Roadmap',
        'KnowledgeBase/FAQ',
        'KnowledgeBase/IPFS',
        'KnowledgeBase/Branding-guide',
        'KnowledgeBase/license',
      ],
    },
    {
      type: 'category',
      label: 'Protocol',
      items: [
        'Protocol/Network-Protocol',
        'Protocol/Components',
        'Protocol/Transactions',
        'Protocol/Intel-SGX',
      ],
    },
    {
      type: 'category',
      label: 'Wallets',
      items: [
        'Wallets/wallet-guide',
        'Wallets/support',
      ],
    },
    {
      type: 'category',
      label: 'Core Modules',
      items: [
        'CoreModules/Uptake',
        'CoreModules/SenaryApp',
        'CoreModules/IDENTT',
      ],
    },
    {
      type: 'category',
      label: 'Client',
      items: [
        'Client/Introduction',
        'Client/Auth',
        'Client/Gov',
        'Client/Bank',
        'Client/Keys',
        'Client/Tendermint',
        'Client/Tx'
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      items: [
        'Developers/Overview',
        'Developers/Setup',
        'Developers/Obtain-Compile-Upload',
        'Developers/Interacting-with-on-chain-contract'
      ]
    },
    {
      type: 'category',
      label: 'Validators',
      items: [
        'Validators/ValidatorsOverview',
        'Validators/hardware-compliance',
        'Validators/vps-compliance',
        'Validators/setup-sgx',
        'Validators/run-full-node',
        'Validators/join-validator-testnet',

      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'Guides/Installation',
        'Guides/Initialization',
        'Guides/Denali',
        'Guides/Keys',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'Resources/References',
      ],
    },
  ],

};

module.exports = sidebars;
